"""init models

Revision ID: ed4d033e4966
Revises: 
Create Date: 2025-10-21 15:58:47.209526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4d033e4966'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradecodes',
    sa.Column('exchange_id', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id')
    )
    op.create_table('tradestrategys',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tradetypes',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('hash_password', sa.String(length=512), nullable=False),
    sa.Column('last_login_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('trades',
    sa.Column('date_open', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_close', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trade_open', sa.Float(), nullable=False),
    sa.Column('trade_close', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('trade_type_id', sa.Integer(), nullable=False),
    sa.Column('trade_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['trade_code_id'], ['tradecodes.id'], ),
    sa.ForeignKeyConstraint(['trade_type_id'], ['tradetypes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usertradecodes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_code_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['trade_code_id'], ['tradecodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trade_code_id', name='uq_user_trade_code')
    )
    op.create_table('usertradestrategys',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_strategy_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['trade_strategy_id'], ['tradestrategys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trade_strategy_id', name='uq_user_trade_strategy')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usertradestrategys')
    op.drop_table('usertradecodes')
    op.drop_table('trades')
    op.drop_table('users')
    op.drop_table('tradetypes')
    op.drop_table('tradestrategys')
    op.drop_table('tradecodes')
    # ### end Alembic commands ###
